# Header
menu:
  首页: /
  归档: /archives
  示例: /code
  关于: /about

# SubNav
subnav:
  github: "https://github.com/seayxu"
  weibo: "http://weibo.com/5600137615"
  rss: "/atom.xml"
  zhihu: "http://www.zhihu.com/people/seayxu"
  mail: "xu@seay.me"
  facebook: "https://facebook.com/iseayxu"
  google: "https://plus.google.com/u/0/112748204150183693089"
  twitter: "https://twitter.com/seayxu"
  linkedin: "https://www.linkedin.com/in/seayxu"
  #douban: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: img/favicon.ico

#你的头像url
avatar: img/author.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: git-seay
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  个人站点: http://seay.me
  Github: https://github.com/seayxu
  Gitcafe: https://gitcafe.com/seay
  博客园: http://www.cnblogs.com/seayxu

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: I like coding!
