language: node_js
node_js:
- "4"
branches:
  only:
  - dev
cache:
  directories:
    - node_modules
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
- openssl aes-256-cbc -K $encrypted_9088a3538b99_key -iv $encrypted_9088a3538b99_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "SeayXu"
- git config --global user.email SeayXu@163.com
install:
- npm install
script:
- npm run deploy  # hexo clean && hexo g -d