# 指定环境
language: node_js

node_js:
- '0.12' #指定使用 node.js 最新的稳定版0.12

# 指定分支
branches:
  only:
  - master #这个分支应当使用自己的 Dev repo

before_install:
#注意将xxxx内容修改为你之前获得的解密参数
- openssl aes-256-cbc -K $encrypted_6f0a1427bcb7_key -iv $encrypted_6f0a1427bcb7_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa_seayxu.blog.git //修改目录权限
- eval $(ssh-agent)//将密钥加入系统
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config //修改 git 信息
- git config --global user.name "SeayXu"
- git config --global user.email SeayXu@gmail.com

# 配置 Hexo
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-deployer-git --save

# 执行 Hexo 的编译操作
script:
- hexo clean
- hexo g
- hexo d
