##### Menu
menu:
  首页: /
  归档: /archives
  示例: /code
  关于: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets:
- github-card
- category
- tag
- links
#- douban
- rss
- weibo
  ## provide eight widgets:github-card,category,tag,rss,archive,tagcloud,links,weibo



#### RSS
rss: /atom.xml #RSS address.

#### Image
imglogo:
  enable: false             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.
apple_icon: img/apple.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture
### Theme Color
theme_color:
    theme: '#2ca6cb'    ##the defaut theme color is blue

# 代码高亮主题
# available: default | night
highlight_theme: default

#### index post is expanding or not
index:
  expand: false          ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: 查看全文

close_aside: false  #close sidebar in post page if true
mathjax: false      #enable mathjax if true

### Creative Commons License Support, see http://creativecommons.org/
### you can choose: by , by-nc , by-nc-nd , by-nc-sa , by-nd , by-sa , zero
creative_commons: by-sa

#### Author information
author:
  intro_line1:  "Hello ,I'm Seay."    ## your introduction on the bottom of the page
  intro_line2:  "This is my git blog."  ## the 2nd line
  weibo: 5600137615     ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  weibo_verifier: b1538d55   ## e.g. b3593ceb Your weibo-show widget verifier ,if you use weibo-show it is needed.
  tsina: 5600137615      ## e.g. 2176287895  Your weibo ID,It will be used in share button.o-show it is needed.
  sinakey: 2063936778      ## share origin.
  zhihu: seayxu ## e.g. jark  for http://www.zhihu.com/people/jark
  email: xu@seay.me     ## e.g. imjark@gmail.com
  twitter: seayxu   ## e.g. jarkwu for https://twitter.com/jarkwu
  github: seayxu     ## e.g. wuchong for https://github.com/wuchong
  facebook: iseayxu   ## e.g. imjark for https://facebook.com/imjark
  linkedin: seayxu   ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
  google_plus: "112748204150183693089"   ## e.g. "111190881341800841449" for https://plus.google.com/111190881341800841449, the "" is needed!
  stackoverflow: 5826591  ## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
  segmentfault: seay ## e.g. seay for http://segmentfault.com/u/seay
  douban:     ## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014
## if you set them, the corresponding  share button will show on the footer

### beian info
beian:
  enable: true
  ga:
    enable: true
    area: 鄂
    no: "42032202000124"
    img: http://beian.gov.cn/img/ghs.png
  domain:
    enable: true
    no: 鄂ICP备13012446号-2

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  个人站点: http://seay.me
  Github: https://github.com/seayxu
  博客园: http://www.cnblogs.com/seayxu
  Feed: /atom.xml
  SiteMap: /sitemap.xml


#### Comment
duoshuo_shortname: git-seay    ## e.g. wuchong   your duoshuo short name.
disqus_shortname:     ## e.g. wuchong   your disqus short name.

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID.
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: false
  id:        ## e.g. UA-46321946-2 your google analytics ID.
  site:      ## e.g. wuchong.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
amazingcounters:
  enable: true
  siteid: 3199339
baidu_tongji:
  enable: true
  sitecode: 9b96c361201736e1a9c6e8d2b8673b3d ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code
cnzz_tongji:
  enable: true
  siteid: 1257185775   ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true


#### Custom Search
google_cse:
  enable: false
  cx:   ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search
## title: search
## ---
baidu_search:     ## http://zn.baidu.com/
  enable: false
  id:   ## e.g. "783281470518440642"  for your baidu search id
  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site

tinysou_search:     ## http://tinysou.com/
  enable: false
  id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id
